title: Andrea Della Corte

description: Life coach & aspiring expert

url: https://dellacorte.me
baseurl: https://dellacorte.me

twitter_username: adielleci

plugins:
  - jekyll-feed
  - jekyll-sitemap

author: Andrea Della Corte

collections:
  books:
    output: true
  principles:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:categories/:title/
