title: Andrea Della Corte

description: Organisational coach & aspiring expert

url: https://dellacorte.me

images: static/imgs
docs: static/docs

github: https://github.com/andreadellacorte/andreadellacorte.github.io/tree/master/

twitter_username: adielleci

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-compress-images

author: Andrea Della Corte

collections:
  books:
    output: true
  presentations:
    output: true
  categoriess:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:categories/:title/
  - scope:
      path: ""
      type: "categoriess"
    values:
      permalink: /categories/:title/

compress_images:
  images_path: "static/imgs/**/*.{gif,png,jpg,jpeg,svg}"
