title: adielleci is Andrea Della Corte

description: Andrea Della Corte's blog

url: https://andreadellacorte.github.io

plugins:
  - jekyll-feed

author: andreadellacorte

collections:
  books:
    output: true

defaults:
  - scope:
      path: ""
      type: "books"
    values:
      layout: book

permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:year/:month/:day/:title/
