
name: adielleci is Andrea Della Corte

description: Andrea Della Corte's blog

url: https://andreadellacorte.github.io

plugins:
  - jekyll-feed

author:
  andreadellacorte

collections:
  books:
    output: true

defaults:
  - scope:
      path: ""
      type: "books"
    values:
      layout: book
