title: adielleci is Andrea Della Corte

description: Andrea Della Corte's blog

url: https://dellacorte.me

twitter_username: adielleci

plugins:
  - jekyll-feed
  - jekyll-sitemap

author: andreadellacorte

collections:
  books:
    output: true
  principles:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: principles/:categories/:title/
