
name: adielleci is Andrea Della Corte

description: Andrea Della Corte's blog

url: https://andreadellacorte.github.io

plugins:
  - jekyll-feed

author:
  andreadellacorte

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
