title: adielleci is Andrea Della Corte

description: Andrea Della Corte's blog

url: https://dellacorte.me

twitter_username: adielleci

plugins:
  - jekyll-feed
  - jekyll-sitemap

author: andreadellacorte

collections:
  books:
    output: true

defaults:
  - scope:
      path: ""
      type: "books"
    values:
      layout: book
      permalink: :collections/:title

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:year/:month/:day/:title/
